#     Copyright (c) 2003-2011 by David W. Caress and Dale N. Chayes (dale@ldeo.columbia.edu)

### sets locations of vital objects
HTMLDIR = ../../html

CC = cc
CFLAGS = -O3 -funroll-loops -fexpensive-optimizations -I/usr/X11R6/include -Wall -Wimplicit -pedantic -W -Wstrict-prototypes -Wredundant-decls  -Wimplicit-int -Wimplicit-function-declaration -Wnested-externs -DBYTESWAPPED 
ARCHIVE = ar rcv

all:
	make_mbhtml

clean:
	rm -f man2html
