#     Copyright (c) 1993-2011 by  David W. Caress and Dale N. Chayes 

BINDIR = ../../bin
LIBDIR = ../../lib
INCDIR = ../../include

### make all makes the MB-system macros and man pages
all:	$(BINDIR)/mbm_xbt \
	$(BINDIR)/mbm_plot \
	$(BINDIR)/mbm_grdplot \
	$(BINDIR)/mbm_grd3dplot \
	$(BINDIR)/mbm_xyplot \
	$(BINDIR)/mbm_stat \
	$(BINDIR)/mbm_grid \
	$(BINDIR)/mbm_grd2arc \
	$(BINDIR)/mbm_arc2grd \
	$(BINDIR)/mbm_grdcut \
	$(BINDIR)/mbm_grdinfo \
	$(BINDIR)/mbm_grdtiff \
	$(BINDIR)/mbm_utm \
	$(BINDIR)/mbm_grd2geovrml \
	$(BINDIR)/mbm_copy \
	$(BINDIR)/mbm_route2mission \
	$(BINDIR)/mbm_makedatalist \
	$(BINDIR)/mbm_histplot \
	$(BINDIR)/mbm_multiprocess \
	$(BINDIR)/mbm_multidatalist \
	$(BINDIR)/mbm_multicopy \
	$(BINDIR)/mbm_bpr


### make clean does nothing
clean:

### link or copy the executables
$(BINDIR)/mbm_xbt:	mbm_xbt.pl
	cp mbm_xbt.pl $(BINDIR)/mbm_xbt
	chmod 775 $(BINDIR)/mbm_xbt
$(BINDIR)/mbm_plot:	mbm_plot.pl
	cp mbm_plot.pl $(BINDIR)/mbm_plot
	chmod 775 $(BINDIR)/mbm_plot
$(BINDIR)/mbm_grdplot:	mbm_grdplot.pl
	cp mbm_grdplot.pl $(BINDIR)/mbm_grdplot
	chmod 775 $(BINDIR)/mbm_grdplot
$(BINDIR)/mbm_grd3dplot:	mbm_grd3dplot.pl
	cp mbm_grd3dplot.pl $(BINDIR)/mbm_grd3dplot
	chmod 775 $(BINDIR)/mbm_grd3dplot
$(BINDIR)/mbm_xyplot:	mbm_xyplot.pl
	cp mbm_xyplot.pl $(BINDIR)/mbm_xyplot
	chmod 775 $(BINDIR)/mbm_xyplot
$(BINDIR)/mbm_stat:	mbm_stat.pl
	cp mbm_stat.pl $(BINDIR)/mbm_stat
	chmod 775 $(BINDIR)/mbm_stat
$(BINDIR)/mbm_grid:	mbm_grid.pl
	cp mbm_grid.pl $(BINDIR)/mbm_grid
	chmod 775 $(BINDIR)/mbm_grid
$(BINDIR)/mbm_grd2arc:	mbm_grd2arc.pl
	cp mbm_grd2arc.pl $(BINDIR)/mbm_grd2arc
	chmod 775 $(BINDIR)/mbm_grd2arc
$(BINDIR)/mbm_arc2grd:	mbm_arc2grd.pl
	cp mbm_arc2grd.pl $(BINDIR)/mbm_arc2grd
	chmod 775 $(BINDIR)/mbm_arc2grd
$(BINDIR)/mbm_grdcut:	mbm_grdcut.pl
	cp mbm_grdcut.pl $(BINDIR)/mbm_grdcut
	chmod 775 $(BINDIR)/mbm_grdcut
$(BINDIR)/mbm_grdinfo:	mbm_grdinfo.pl
	cp mbm_grdinfo.pl $(BINDIR)/mbm_grdinfo
	chmod 775 $(BINDIR)/mbm_grdinfo
$(BINDIR)/mbm_grdtiff:	mbm_grdtiff.pl
	cp mbm_grdtiff.pl $(BINDIR)/mbm_grdtiff
	chmod 775 $(BINDIR)/mbm_grdtiff
$(BINDIR)/mbm_utm:	mbm_utm.pl
	cp mbm_utm.pl $(BINDIR)/mbm_utm
	chmod 775 $(BINDIR)/mbm_utm
$(BINDIR)/mbm_grd2geovrml:	mbm_grd2geovrml.pl
	cp mbm_grd2geovrml.pl $(BINDIR)/mbm_grd2geovrml
	chmod 775 $(BINDIR)/mbm_grd2geovrml
$(BINDIR)/mbm_copy:	mbm_copy.pl
	cp mbm_copy.pl $(BINDIR)/mbm_copy
	chmod 775 $(BINDIR)/mbm_copy
$(BINDIR)/mbm_route2mission:	mbm_route2mission.pl
	cp mbm_route2mission.pl $(BINDIR)/mbm_route2mission
	chmod 775 $(BINDIR)/mbm_route2mission
$(BINDIR)/mbm_makedatalist:	mbm_makedatalist.pl
	cp mbm_makedatalist.pl $(BINDIR)/mbm_makedatalist
	chmod 775 $(BINDIR)/mbm_makedatalist
$(BINDIR)/mbm_histplot:	mbm_histplot.pl
	cp mbm_histplot.pl $(BINDIR)/mbm_histplot
	chmod 775 $(BINDIR)/mbm_histplot
$(BINDIR)/mbm_multiprocess:	mbm_multiprocess.pl
	cp mbm_multiprocess.pl $(BINDIR)/mbm_multiprocess
	chmod 775 $(BINDIR)/mbm_multiprocess
$(BINDIR)/mbm_multidatalist:	mbm_multidatalist.pl
	cp mbm_multidatalist.pl $(BINDIR)/mbm_multidatalist
	chmod 775 $(BINDIR)/mbm_multidatalist
$(BINDIR)/mbm_multicopy:	mbm_multicopy.pl
	cp mbm_multicopy.pl $(BINDIR)/mbm_multicopy
	chmod 775 $(BINDIR)/mbm_multicopy
$(BINDIR)/mbm_bpr:	mbm_bpr.pl
	cp mbm_bpr.pl $(BINDIR)/mbm_bpr
	chmod 775 $(BINDIR)/mbm_bpr
