#     Copyright (c) 1993-2011 David W. Caress and Dale N. Chayes

all:
	cd surf; make all
	cd mr1pr; make all
	cd proj; make all
	cd mbio; make all
	cd mbaux; make all
	cd utilities; make all
	cd gmt; make all
	cd macros; make all
	cd mbedit; make all
	cd mbnavedit; make all
	cd mbnavadjust; make all
	cd mbvelocitytool; make all
	cd mbview; make all
	cd otps; make all

clean:
	- cd surf; make clean
	- cd mr1pr; make clean
	- cd proj; make clean
	- cd mbio; make clean
	- cd mbaux; make clean
	- cd utilities; make clean
	- cd gmt; make clean
	- cd macros; make clean
	- cd mbedit; make clean
	- cd mbnavedit; make clean
	- cd mbnavadjust; make clean
	- cd mbvelocitytool; make clean
	- cd mbview; make clean
	- cd otps; make clean

